const VERTICAL_GUTTER_SIZE_PX = 20;
const HORIZONTAL_GUTTER_SIZE_PX = 20;
const PAGE_HEIGHT = 792;
const PDF_WIDTH_PERCENTAGE = 56;
const PDF_HEIGHT_PERCENTAGE = 94;
const OBSERVER_THRESHOLD_PERCENTAGE = 0.4;
const PDF_HEADER_SIZE_PX = 44;
const PDF_SIDEBAR_SIZE_PX = 80;

export const PDF_DISPLAY_DEFAULTS = {
  VERTICAL_GUTTER_SIZE_PX,
  HORIZONTAL_GUTTER_SIZE_PX,
  PAGE_HEIGHT,
  PDF_WIDTH_PERCENTAGE,
  PDF_HEIGHT_PERCENTAGE,
  OBSERVER_THRESHOLD_PERCENTAGE,
  PDF_HEADER_SIZE_PX,
  PDF_SIDEBAR_SIZE_PX,
} as const;
